### ISSUE TITLE
Broken Zenodo DOI link?

### ISSUE THREAD

**Issue by bonnland** [ProjectPythia/na-cordex-viz-cookbook#8]
Hi, 

The nightly build looks like it is failing on some link checks, including this link found in README.md:

https://zenodo.org/badge/635958518.svg

Is this supposed to be a DOI for this particular cookbook?

**Comment by brian-rose** [comment]
Yes, the badge will work as soon as a DOI is minted for this repo on Zenodo. We have some automation for this. But we've also started masking out the zenodo URL from the link checker to avoid these annoying failures. I will open a PR for that here.

**Comment by brian-rose** [comment]
@bonnland it looks to me like this cookbook is ripe for inclusion in the [gallery](https://cookbooks.projectpythia.org). We're in the midst of setting up a more clearly-defined review process for this. Are you game for this cookbook to serve as a test case for the new review cycle? (It might be a couple of weeks yet before any action is taken)

**Comment by bonnland** [comment]
Absolutely; happy if this helps somehow!

**Comment by brian-rose** [comment]
> Absolutely; happy if this helps somehow!

Great, I'll open a new issue here to identify this cookbook as a test case. Thanks for your patience!
